services:
  - type: web
    name: task-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn taskproject.wsgi
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your_secret_key
